-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "companyName" TEXT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" TEXT NOT NULL DEFAULT 'client';

-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "active" BOOLEAN NOT NULL DEFAULT true;
